### ISSUE TITLE
Better color syntax ?

### ISSUE THREAD

**Issue by cyrilbosson** [EmranMR/Laravel-Nova-Extension#14]
Hello @EmranMR ,

Thanks for your plugin!

A few possible improvements to increase visibility:
- brackets should be in purple
- as" should be in purple
- a specific color (or purple?) for "{{ }}".

<img width="456" alt="Capture d’écran 2023-08-31 à 10 05 17" src="https://github.com/EmranMR/Laravel-Nova-Extension/assets/36671933/278402e9-ec0d-41e4-95db-551064729b56">

What do you think?

**Comment by EmranMR** [comment]
Hey @cyrilbosson 👋

So I totally agree, but unfortunately most of your requests, although **doable** would be outwith this extension (apart from the third bulletpoint).
Please find the explanation below for each of the bullet points for clarification, as you will see its a bit of a yin yang ☯︎:

## 1. brackets colouring ✅ ❌
This is already supported, built-in Nova. However there is a caveat would also relate to your **third** request see below.

All you have to toggle the following in your settings:
```
Settings > Editor > Use rainbow brackets
```
<img width="501" alt="Screenshot 2023-08-31 at 22 13 00" src="https://github.com/EmranMR/Laravel-Nova-Extension/assets/11975985/c649e20b-3f40-4589-af1e-8f9be9a183ee">

This is my own default setting but, as you can see there is only one problem, the `{{}}` ...😑
We have already issued a **feature request** for this on [Nova Devforum](https://devforum.nova.app/t/multiple-characters-bracket/2108), so please feel free to add your +1 there as well. At the moment, it is not possible to define multi-character. Basically Nova doesn't realise not to rainbow that, even if I define the bracket `{{` and `}}`  in the Syntax def.

## 3.  Specific colour for`{{}}` ✅❌: 
However I will add a support for something like the following:
> ⚠️ User needs to disable rainbow bracket. otherwise it will override everything I am doing below giving the same result as above.

- Based on the way [tree-sitter-blade](https://github.com/EmranMR/tree-sitter-blade) is defined (intentionally exactly for this reason) I could grab the brackets and add a theme selector (bracket) to it **but**:
1. Most of the themes are not so great with their `bracket` colouring 😑. 
2. There is also another problem, I can highlight `{{}}` but all the other brackets would stay neutral because the rainbow bracket is disabled and responsible for this...

So below is in Monokai and I just used `tag.framework` selector just to show what I mean by NO 1 above:
<img width="501" alt="Screenshot 2023-08-31 at 22 21 40" src="https://github.com/EmranMR/Laravel-Nova-Extension/assets/11975985/d2540a30-a3df-4031-8bb3-395640384a83">

I will add support using the correct semantic selector `bracket` in my next update 👍,  but I am yet to find a theme that does a good job with `brackets`. For example here is monokai with `bracket` but the colour is definitely not my choice:
<img width="501" alt="Screenshot 2023-08-31 at 22 28 32" src="https://github.com/EmranMR/Laravel-Nova-Extension/assets/11975985/914ea0ef-0737-4ee9-8015-62501f0d807a">

## 2. `as` being highlighted:
This is outwith this extension, we just need a great theme and designer, specifically for Laravel and PHP 👀. The internal source code responsible for `tree-sitter-php` actually provides the facility for the targeting/theming. The theme authors just need to define a `keyword` in their definition. For example see below for the new theme,  [Synthe Wave](https://extensions.panic.com/extensions/brewend/brewend.synthwave/) which is a PHP orientated theme. As you can see `as` is differently coloured
<img width="501" alt="Screenshot 2023-08-31 at 22 40 18" src="https://github.com/EmranMR/Laravel-Nova-Extension/assets/11975985/71cdc19c-527e-4f29-acf2-ec1ced267134">

Do let me know if you find a good theme for PHP/Laravel here as I am struggling to find one that, is minimalist like Monokai but a bit more feature rich towards PHP. 😊

**Comment by EmranMR** [comment]
> There is also another problem, I can highlight {{}} but all the other brackets would stay neutral because the rainbow bracket is disabled and responsible for this...

I found a way to fix the issue relating to the quote above. ie, all brackets will be available for grab by the themes for highlighting in the next update. Again subject to users having the "rainbow bracket" off! 

I just have to adjust the `tree-sitter-blade` grammar, and we will be all good to go 😉.

<img width="486" alt="Screenshot 2023-09-01 at 21 02 39" src="https://github.com/EmranMR/Laravel-Nova-Extension/assets/11975985/b2ad50cb-c21e-497d-8755-d2522e82c9fe">
