### ISSUE TITLE
Comment out a line

### ISSUE THREAD

**Issue by nam-co** [EmranMR/Laravel-Nova-Extension#18]
Hi thank you for the extension, I was wondering if there's a way toggle comment lines or blocks of code like in VScode, where you just select and do command + / , and the the code is {{-- --}}

This could be great

**Comment by EmranMR** [comment]
Hi @nam-co !
Thank you for your comment. Unfortunately this is an annoying limitation with Nova, and I am really sure they **can** fix...

[I raised this issue with Nova on the forum back in June](https://devforum.nova.app/t/comment-shortcut-improvement-in-complex-comment-situations-in-tree-sitter-based-syntax-extension/2220), but they just ignored my suggestion/put it at the bottom of their list. Pretty much like my other requests 😅. 
May I ask if you could kindly, **leave a comment** or **+1** in the forum to get their attention 👀 😂

For time being I had **2 alternatives** in mind to implement as a temporary measure:
1. Create a **snippet**, that maps to **another comment shortcut**? (not sure if I can override the Nova comment shortcut just in `blade` files or I would have to sort out an alternative comment shortcut maybe `ctrl+/`)
2. Or **autocompletion**, ie, user types `{{-` and gets a suggestion, which can expand upon return?
3. or both?? 

what would you think would be the best option Ux wise?

P.S, I actually believe this limitation is very likely related to the #10 🐞 as well. If Panic fix this, they will prob very likely fix #10  as well, or vice versa. It is to do with the way they implemented the tree-sitter injection. I would be very interested to see if this is the same case with NeoVim users of the grammar 🤔

**Comment by nam-co** [comment]
What do you think @foozmeat and @logancollins ? the app has come a long way

**Comment by EmranMR** [comment]
> and twitter (aka X), and they probably won't see it, they use to respond very fast in the beta days

Yea I don't think they are using [twitter for support anymore](https://x.com/panic/status/1658933488245153800?s=46&t=PuWDf9oqZRvFu6Jq73uQMA). Best bet is emailing at the moment 😊

**Comment by nam-co** [comment]
@EmranMR have you ever gotten something like this?
<img width="418" alt="Screenshot 2023-10-05 at 9 37 52 AM" src="https://github.com/EmranMR/Laravel-Nova-Extension/assets/3951529/d200a7d3-25fa-414c-b3db-6489d9461d6e">

**Comment by EmranMR** [comment]
Wow haha 😅 god no! That is mental! 
Although, there was a bug that maxed my CPU to 400%  a couple of months.  💣🎆

There has been a lot of crashes recently with the new version. Definitely report that via email or [maybe put on the forum here](https://devforum.nova.app/t/frequent-crashes/2394/10)? Everyone seem to just put it under this topic rather than creating a new one, so that it is easier for the team at Panic to assess I suppose.

Mike from Panic, asked me to sample using these steps and send the data as a reply, maybe just do this when it happens again and report the problem using `help>report problem or feature request`

>1. While the problem is occurring, please launch Activity Monitor on your Mac (found in /Applications/Utilities).
>2. In the list of processes, select Nova. (You can search Activity Monitor in the top right to help you find it.)
>3. In Activity Monitor's toolbar, click the (...) icon, and select "Sample Process".
>4. After Activity Monitor finishes collecting its sample, you'll see a window with a text log. Click "Save" in the top right to save the sample to a file.

**Comment by EmranMR** [comment]
> There has been a lot of crashes recently with the new version. Definitely report that via email or [maybe put on the forum here](https://devforum.nova.app/t/frequent-crashes/2394/10)?

Someone actually reported the memory leak today on the forum, so I would suggest [subscribe/comment or follow on here](https://devforum.nova.app/t/memory-leak-during-syntax-development/1608) 👍

**Comment by logancollins** [comment]
> [I raised this issue with Nova on the forum back in June](https://devforum.nova.app/t/comment-shortcut-improvement-in-complex-comment-situations-in-tree-sitter-based-syntax-extension/2220), but they just ignored my suggestion/put it at the bottom of their list. Pretty much like my other requests 😅.

We are not ignoring you requests. Nova has one full-time engineer and one full-time support advocate, and unfortunately the list of issues, suggestions, and questions from users for an app like Nova is large. We prioritize issues based on their time sensitivity and severity as best we can, and thank our users for their patience.

**Comment by EmranMR** [comment]
> I would be very interested to see if this is the same case with NeoVim users of the grammar 🤔

@nam-co I just checked with a Neovim user and I can confirm they have the same issue when they use the comment shortcut, so it is not limited to Nova. 😊

@logancollins thank you for your comment! I understand, that is why I said "put at the bottom of the list" as well  👀. 
At least for my extensions, like other devs, I always try to find a way around the issues using temporary measures, until the features arrive. 

Engineering Nova is a **humongous** task for just **ONE** full-time engineer. 
Like other users, I still can not believe the amount of milestones you have managed to achieve solo, in such **short amount of time**.  The git integration, tree-sitter implementation and the list goes on; along the way bug fixes, API development, Icarus  it is like truly mind blowing 🤯😂. 
I really hope one day I could achieve the same level of sophistication in engineering one day, I would even be happy with half of it 😅!

I just sincerely, really wished Panic, employed more engineers and support staff to work under  your watch. So please feel free to pass my feedback to the managements etc. 

The issue is Jetbrains have thousands of employed engineers, the VsCode or NVim  thousands of contributors, Zed is the same. It is just not fair  😬 I am personally certain they will see the return on investment very quickly, because to be honest, Nova is so close to perfection. 👌

**Comment by EmranMR** [comment]
Hi, @nam-co  I added a couple of shortcuts, completion for comments.  You can read about how to use the alternatives in the `README` file

I did not do the following due to some snippet based limitations:
1. Commenting the _text before_  cursor (If there was a white space, it did not work, unlike the normal `cmd+/`
2. Commenting the _selected text_ (did not work with vim mode properly)
3. The default values for snippet variables did not work, ie if no text was selected, the cursor was positioned after the comment tags 

If all good, do let me know and I will close this issue 👍

**Comment by nam-co** [comment]
@logancollins thanks for the response, I understand, maybe lowering the price could get a bigger audience = more revenue = more developers = more parties and features ... just an idea, the app being native had a lot going for it, thanks for the app

@EmranMR thanks for the chat and the work, I will try it, have a great day 👍
