### ISSUE TITLE
@endguest keyword does not appear to highlight correctly

### ISSUE THREAD

**Issue by chipotle** [EmranMR/Laravel-Nova-Extension#23]
I'm seeing that `@auth...@endauth` blocks get the keywords highlighted, but in `@guest...@endguest` blocks, only `@guest` is highlighted and `@endguest` is just normal text.

This is in Nova 12b2, for the record, so it may be a beta bug. A look at your extension code suggests that it *should* be highlighting correctly, although I confess my understanding of Nova's tree-sitter integration is very fuzzy.

**Comment by chipotle** [comment]
This seems, upon further poking around, to be an oddity in how Nova's highlighting in this instance works, and nothing to do with the extension at all. Sorry!

**Comment by EmranMR** [comment]
@chipotle Mmm that is quite odd. so is it fixed? Because it might be tree-sitter-blade issue. 

Also I did not know Nova 12 beta is out and about!

I will see if I can get my hands on it and run some tests. very likely the extension breaks a bit, because Logan was working to update the tree-sitter-php, which in turn brings php-only support as first party, rather than the hacky implementation of mine lol.
